services:
  # --- Web UI (Streamlit) ---
  - type: web
    name: grantfinder-vic
    env: python
    plan: starter                     # disk requires a paid plan
    buildCommand: |
      python -V
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATA_DIR
        value: /var/data/grants       # <-- app should write here
    disk:
      name: grants-data
      mountPath: /var/data            # shared mount for CSV
      sizeGB: 1

  # --- Hourly refresher (shared disk) ---
  - type: worker
    name: grantfinder-vic-hourly
    env: python
    plan: starter                     # disk requires a paid plan
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    # Run the refresh script every hour forever
    startCommand: bash -lc 'while true; do python refresh.py; sleep 3600; done'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATA_DIR
        value: /var/data/grants       # same path as web
    disk:
      name: grants-data               # same disk name = shared storage
      mountPath: /var/data
      sizeGB: 1
