name: Supabase Refresh (Hourly)

on:
  schedule:
    - cron: "0 * * * *"   # every hour (UTC)
  workflow_dispatch: {}

jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If you want a minimal install instead, use:
          # pip install requests beautifulsoup4 python-dateutil pyyaml supabase openai

      - name: Run refresh
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          FOLLOW_DETAILS: "25"
          SUMMARIZE: "0"
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # only if SUMMARIZE=1
          TENANTS_FILE: "tenants.yaml"
        run: python refresh_supabase.py
